# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-04 12:59
from __future__ import unicode_literals

import ditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180105_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ditor.models.UEditorField(blank=True, default='', verbose_name='内容'),
        ),
    ]
