# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-05 12:31
from __future__ import unicode_literals

import ditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180204_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ditor.models.UEditorField(blank=True, default='', max_length=1024000000000, verbose_name='内容'),
        ),
    ]
